export default {
  PORT: process.env.PORT,
  DB_URI: process.env.DB_URI,
  SUPER_ADMIN_PASSWORD: process.env.SUPER_ADMIN_PASSWORD,
  SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL,
  JWT_SECRET: process.env.JWT_SECRET,
  API_HOST: process.env.API_HOST,
  MAIL_HOST: process.env.MAIL_HOST,
  MAIL_PASS: process.env.MAIL_PASS,
  MAIL_USER: process.env.MAIL_USER,
  MAIL_FROM: process.env.MAIL_FROM,
  MAIL_PORT: process.env.MAIL_PORT,
  SERVICE_ID: process.env.SERVICE_ID,
  TAP_API_KEY: process.env.TAP_API_KEY,
  TAP_BASE_URL: process.env.TAP_BASE_URL,
  CLIENT_URL: process.env.CLIENT_URL,
  CLOUD_NAME: process.env.CLOUD_NAME,
  CLOUD_API_KEY: process.env.CLOUD_API_KEY,
  CLOUD_API_SECRET: process.env.CLOUD_API_SECRET,
  PUBLIC_JWK: process.env.PUBLIC_JWK,
  PRIVATE_JWK: process.env.PRIVATE_JWK,
  AES_KEY: process.env.AES_KEY,
};
