import crypto from "node:crypto";
import { BankConnector, CanonicalBankTransaction, VerifiedBankEvent } from "./bank.connector";

function transaction(data:Record<string,any>):CanonicalBankTransaction{const rawStatus=String(data.transactionStatus??data.processingStatus??"SUCCESS").toUpperCase();return{providerTransactionId:String(data.transactionReference??data.reference),status:rawStatus==="PENDING"?"pending":rawStatus==="REVERSED"||rawStatus==="CANCELLED"?"reversed":"booked",direction:String(data.direction??"credit").toLowerCase()==="debit"?"debit":"credit",amount:Number(data.amount??data.actualAmount??0),currency:String(data.currency??"NGN").toUpperCase(),description:String(data.description??data.responseMessage??data.transactionType??"Moniepoint transaction"),narration:String(data.narration??data.description??""),reference:String(data.merchantReference??data.reference??""),sessionId:data.sessionId?String(data.sessionId):undefined,counterpartyName:data.counterpartyName?String(data.counterpartyName):undefined,counterpartyBank:data.counterpartyBank?String(data.counterpartyBank):undefined,counterpartyAccountMasked:data.counterpartyAccountMasked?String(data.counterpartyAccountMasked):undefined,transactedAt:String(data.transactionTime??data.transactedAt??new Date().toISOString()),bookedAt:rawStatus==="PENDING"?undefined:String(data.bookedAt??data.transactionTime??new Date().toISOString()),runningBalance:data.runningBalance==null?undefined:Number(data.runningBalance)};}

export class MockMoniepointConnector implements BankConnector{readonly provider="moniepoint";verifyAndNormalize(raw:Buffer,headers:Record<string,string|undefined>,secret="mock-moniepoint-secret"):VerifiedBankEvent{const id=headers["moniepoint-webhook-id"]??"";const timestamp=headers["moniepoint-webhook-timestamp"]??"";const supplied=headers["moniepoint-webhook-signature"]??"";const expected=crypto.createHmac("sha256",secret).update(`${id}__${timestamp}__${raw.toString("utf8")}`).digest("base64");if(!id||!timestamp||supplied.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected)))throw new Error("INVALID_SIGNATURE");const payload=JSON.parse(raw.toString("utf8")) as Record<string,any>;const data=payload.data??payload;return{eventId:String(payload.eventId??id),eventType:String(payload.eventType??"V1_BANK_TRANSACTION"),occurredAt:String(payload.createdAt??data.transactionTime??new Date().toISOString()),transactions:[transaction(data)],raw:payload};}}

export const mockMoniepoint=new MockMoniepointConnector();

