import { KeyboardEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown2, CloseCircle, SearchNormal1, TickCircle } from "iconsax-react";

export type SelectionOption = { id:string; title:string; subtitle?:string; meta?:string; keywords?:string; disabled?:boolean };

export function SearchSelection({label,value,options,onChange,placeholder="Choose an option",searchPlaceholder="Search",emptyTitle="No results found",disabled=false}:{label:string;value:string;options:SelectionOption[];onChange:(value:string)=>void;placeholder?:string;searchPlaceholder?:string;emptyTitle?:string;disabled?:boolean}){
  const [open,setOpen]=useState(false);const [search,setSearch]=useState("");const [limit,setLimit]=useState(50);const [active,setActive]=useState(0);const searchRef=useRef<HTMLInputElement>(null);const modalRef=useRef<HTMLElement>(null);const selected=options.find(option=>option.id===value);
  const filtered=useMemo(()=>{const terms=search.toLowerCase().trim().split(/\s+/).filter(Boolean);return options.filter(option=>terms.every(term=>`${option.title} ${option.subtitle??""} ${option.meta??""} ${option.keywords??""}`.toLowerCase().includes(term)));},[options,search]);
  const visible=filtered.slice(0,limit);
  useEffect(()=>{if(!open)return;setSearch("");setLimit(50);setActive(0);const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow="hidden";const frame=requestAnimationFrame(()=>searchRef.current?.focus());const keydown=(event:globalThis.KeyboardEvent)=>{if(event.key==="Escape")setOpen(false);if(event.key!=="Tab"||!modalRef.current)return;const controls=[...modalRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!controls.length)return;const first=controls[0]!;const last=controls[controls.length-1]!;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener("keydown",keydown);return()=>{cancelAnimationFrame(frame);document.removeEventListener("keydown",keydown);document.body.style.overflow=overflow;previous?.focus();};},[open]);
  useEffect(()=>setActive(0),[search]);
  function choose(option:SelectionOption){if(option.disabled)return;onChange(option.id);setOpen(false);}
  function keys(event:KeyboardEvent<HTMLInputElement>){if(event.key==="ArrowDown"){event.preventDefault();setActive(index=>Math.min(index+1,visible.length-1));}else if(event.key==="ArrowUp"){event.preventDefault();setActive(index=>Math.max(index-1,0));}else if(event.key==="Enter"&&visible[active]){event.preventDefault();choose(visible[active]!);}}
  return <div className="selection-field"><span className="selection-field__label">{label}</span><button type="button" className="selection-trigger" onClick={()=>setOpen(true)} disabled={disabled} aria-haspopup="dialog"><span>{selected?<><strong>{selected.title}</strong>{selected.subtitle&&<small>{selected.subtitle}</small>}</>:<small>{placeholder}</small>}</span><ArrowDown2 size={17}/></button>{open&&<div className="selection-layer" role="dialog" aria-modal="true" aria-label={label}><button type="button" className="selection-backdrop" onClick={()=>setOpen(false)} aria-label="Close selection"/><section ref={modalRef} className="selection-modal"><header><div><h2>{label}</h2><p>{options.length.toLocaleString()} available</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close"><CloseCircle size={23}/></button></header><div className="selection-search"><SearchNormal1 size={19}/><input ref={searchRef} value={search} onChange={event=>setSearch(event.target.value)} onKeyDown={keys} placeholder={searchPlaceholder} role="combobox" aria-expanded="true" aria-controls="selection-results" aria-activedescendant={visible[active]?`selection-${visible[active]!.id}`:undefined}/>{search&&<button type="button" onClick={()=>setSearch("")}>Clear</button>}</div><div className="selection-results" id="selection-results" role="listbox">{visible.map((option,index)=><button type="button" id={`selection-${option.id}`} role="option" aria-selected={option.id===value} disabled={option.disabled} className={`${index===active?"active":""} ${option.id===value?"selected":""}`} key={option.id} onMouseEnter={()=>setActive(index)} onClick={()=>choose(option)}><span className="selection-avatar">{option.title.charAt(0).toUpperCase()}</span><span><strong>{option.title}</strong>{option.subtitle&&<small>{option.subtitle}</small>}</span>{option.meta&&<em>{option.meta}</em>}{option.id===value&&<TickCircle size={19}/>}</button>)}{!visible.length&&<div className="selection-empty"><SearchNormal1 size={25}/><strong>{emptyTitle}</strong><p>Try a name, email, company, SKU, or description.</p></div>}</div>{filtered.length>limit&&<footer><button type="button" onClick={()=>setLimit(current=>current+50)}>Show 50 more</button><span>Showing {visible.length.toLocaleString()} of {filtered.length.toLocaleString()}</span></footer>}</section></div>}</div>;
}
