import nodemailer from "nodemailer";
import { env } from "../config";
import { HttpError } from "../http";

function escape(value: unknown): string { return String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!); }
export function emailConfigured() { return Boolean(env.smtp.host && env.smtp.user && env.smtp.pass); }

export async function sendInvoiceEmail(invoice: Record<string, any>, lines: Array<Record<string, any>>) {
  if (!emailConfigured()) throw new HttpError(503, "Email delivery is not configured. Add SMTP settings before sending invoices.", "EMAIL_NOT_CONFIGURED");
  const invoiceUrl = `${env.publicWebUrl}/pay/invoice/${invoice.public_token}`;
  const rows = lines.map((line) => `<tr><td style="padding:10px;border-bottom:1px solid #e7ece8">${escape(line.description)}</td><td style="padding:10px;text-align:center;border-bottom:1px solid #e7ece8">${escape(line.quantity)}</td><td style="padding:10px;text-align:right;border-bottom:1px solid #e7ece8">${escape(invoice.currency)} ${Number(line.total).toLocaleString()}</td></tr>`).join("");
  const transporter = nodemailer.createTransport({ host: env.smtp.host, port: env.smtp.port, secure: env.smtp.secure, auth: { user: env.smtp.user, pass: env.smtp.pass } });
  const bank = invoice.virtual_account_number ? `<div style="padding:16px;background:#f5f7f3;border-radius:10px"><strong>Bank transfer</strong><p>${escape(invoice.virtual_bank_name)} · ${escape(invoice.virtual_account_number)}<br>${escape(invoice.virtual_account_name)}</p><small>Use invoice ${escape(invoice.number)} as your payment reference.</small></div>` : "";
  await transporter.sendMail({ from: { name: `${String(invoice.business_name).trim()} via LemonBooks`, address: env.smtp.from }, to: invoice.client_email, subject: `${invoice.business_name} sent you invoice ${invoice.number}`, html: `<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#183028"><div style="padding:28px;background:#174c3c;color:white;border-radius:14px 14px 0 0"><div style="font-size:22px;font-weight:700">LemonBooks</div><p style="margin-bottom:0">Invoice from ${escape(invoice.business_name)}</p></div><div style="padding:28px;border:1px solid #e1e7e2"><p>Hello ${escape(invoice.client_name)},</p><p>${escape(invoice.business_name)} sent you invoice <strong>${escape(invoice.number)}</strong>.</p><table style="width:100%;border-collapse:collapse;margin:22px 0"><thead><tr><th style="padding:10px;text-align:left;background:#f5f7f3">Item</th><th style="padding:10px;background:#f5f7f3">Qty</th><th style="padding:10px;text-align:right;background:#f5f7f3">Amount</th></tr></thead><tbody>${rows}</tbody></table><p style="font-size:20px;font-weight:700;text-align:right">Total: ${escape(invoice.currency)} ${Number(invoice.total).toLocaleString()}</p>${bank}<p style="text-align:center;margin:28px 0"><a href="${invoiceUrl}" style="display:inline-block;padding:14px 22px;border-radius:10px;background:#174c3c;color:white;text-decoration:none;font-weight:700">View invoice and choose payment method</a></p><p style="font-size:12px;color:#68756f">On the secure invoice page you can pay with Paystack, report a cash payment, upload transfer proof, or create a customer account.</p></div></div>` });
}
