import { NextFunction, Request, Response, Router } from "express";
import { env } from "../config";
import { query, transaction } from "../database/pool";
import { asyncRoute, HttpError } from "../http";
import { authenticateMonnify, decryptMonnifyCredentials, encryptMonnifyCredentials, MonnifyEnvironment, monnifyRequest, validMonnifySignature } from "../services/monnify.service";
import { settle } from "./paystack.routes";

export const monnifyRouter = Router();
type Connection = { id:string; business_id:string; environment:MonnifyEnvironment; encrypted_credentials:string };

function manage(role:string){if(!["owner","admin"].includes(role))throw new HttpError(403,"Only an owner or admin can manage payment providers");}
async function connectionForBusiness(businessId:string) {
  const row=(await query<Connection>("SELECT id,business_id,environment,encrypted_credentials FROM integration_connections WHERE business_id=$1 AND kind='payment_provider' AND provider='monnify' AND status='active' AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 1",[businessId]))[0];
  if(!row?.encrypted_credentials)throw new HttpError(409,"Activate Monnify in Business settings first","MONNIFY_NOT_CONNECTED");
  return row;
}
export async function activeMonnify(businessId:string){const connection=await connectionForBusiness(businessId);return{connection,credentials:decryptMonnifyCredentials(connection.encrypted_credentials)};}

monnifyRouter.get("/connection",asyncRoute(async(req,res)=>{const row=(await query<Record<string,any>>("SELECT id,status,environment,external_business_id,capabilities,last_success_at,last_error_code,created_at,updated_at FROM integration_connections WHERE business_id=$1 AND kind='payment_provider' AND provider='monnify' AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 1",[req.auth!.businessId]))[0]??null;res.json({success:true,data:row?{...row,webhookUrl:`${env.publicApiUrl}/api/v3/payments/monnify/webhook/${row.id}`}:null});}));

monnifyRouter.post("/connect",asyncRoute(async(req,res)=>{manage(req.auth!.role);const environment=String(req.body.environment??"sandbox") as MonnifyEnvironment;const credentials={apiKey:String(req.body.apiKey??"").trim(),secretKey:String(req.body.secretKey??"").trim(),contractCode:String(req.body.contractCode??"").trim()};if(!["sandbox","production"].includes(environment)||!credentials.apiKey||!credentials.secretKey||!credentials.contractCode)throw new HttpError(400,"Environment, API key, secret key, and contract code are required");await authenticateMonnify(credentials,environment);const encrypted=encryptMonnifyCredentials(credentials);
  const row=await transaction(async client=>{await client.query("UPDATE integration_connections SET status='revoked',encrypted_credentials=NULL,deleted_at=now(),updated_at=now() WHERE business_id=$1 AND kind='payment_provider' AND provider='monnify' AND deleted_at IS NULL",[req.auth!.businessId]);const result=await client.query<Record<string,any>>(`INSERT INTO integration_connections(business_id,kind,provider,status,environment,external_business_id,capabilities,encrypted_credentials,consent_scope,consented_by,consented_at,last_success_at) VALUES($1,'payment_provider','monnify','active',$2,$3,$4,$5,$6,$7,now(),now()) RETURNING id,status,environment,external_business_id,last_success_at`,[req.auth!.businessId,environment,credentials.contractCode,JSON.stringify({checkout:true,verification:true,webhooks:true}),encrypted,JSON.stringify(["collections"]),req.auth!.userId]);return result.rows[0];});if(!row)throw new HttpError(500,"Monnify connection could not be saved");res.status(201).json({success:true,message:"Monnify activated and credentials verified",data:{...row,webhookUrl:`${env.publicApiUrl}/api/v3/payments/monnify/webhook/${row.id}`}});}));

monnifyRouter.delete("/connection",asyncRoute(async(req,res)=>{manage(req.auth!.role);const row=(await query<{id:string}>("UPDATE integration_connections SET status='revoked',encrypted_credentials=NULL,deleted_at=now(),updated_at=now() WHERE business_id=$1 AND kind='payment_provider' AND provider='monnify' AND deleted_at IS NULL RETURNING id",[req.auth!.businessId]))[0];if(!row)throw new HttpError(404,"Monnify connection not found");res.json({success:true,message:"Monnify disconnected",data:row});}));

monnifyRouter.post("/initialize/:invoiceId",asyncRoute(async(req,res)=>{const {connection,credentials}=await activeMonnify(req.auth!.businessId);const invoice=(await query<Record<string,any>>("SELECT i.*,c.name client_name,c.email client_email FROM invoices i LEFT JOIN clients c ON c.id=i.client_id WHERE i.id=$1 AND i.business_id=$2 AND i.status IN ('sent','part_paid','overdue') AND i.deleted_at IS NULL",[req.params.invoiceId,req.auth!.businessId]))[0];if(!invoice?.client_email)throw new HttpError(400,"A payable invoice with a customer email is required");const amount=Number(invoice.total)-Number(invoice.amount_paid);const reference=`LB-MON-${Date.now()}`;const data=await monnifyRequest<Record<string,string>>(credentials,connection.environment,"/api/v1/merchant/transactions/init-transaction",{method:"POST",body:JSON.stringify({amount,customerName:invoice.client_name,customerEmail:invoice.client_email,paymentReference:reference,paymentDescription:`Invoice ${invoice.number}`,currencyCode:invoice.currency,contractCode:credentials.contractCode,redirectUrl:`${env.publicWebUrl}/payments/monnify/callback`})});await query("INSERT INTO payment_intents(business_id,invoice_id,provider,reference,access_code,authorization_url,amount,currency,provider_payload) VALUES($1,$2,'monnify',$3,$4,$5,$6,$7,$8)",[invoice.business_id,invoice.id,reference,data.transactionReference,data.checkoutUrl,amount,invoice.currency,JSON.stringify(data)]);res.status(201).json({success:true,message:"Monnify checkout created",data:{authorizationUrl:data.checkoutUrl,reference,transactionReference:data.transactionReference}});}));

monnifyRouter.get("/verify/:reference",asyncRoute(async(req,res)=>{const reference=String(req.params.reference);const intent=(await query<Record<string,any>>("SELECT * FROM payment_intents WHERE reference=$1 AND provider='monnify' AND business_id=$2",[reference,req.auth!.businessId]))[0];if(!intent)throw new HttpError(404,"Payment reference not found");const {connection,credentials}=await activeMonnify(intent.business_id);const data=await monnifyRequest<Record<string,any>>(credentials,connection.environment,`/api/v2/transactions/${encodeURIComponent(String(intent.access_code))}`);const normalized={...data,status:data.paymentStatus==="PAID"?"success":"pending",amount:Math.round(Number(data.amountPaid??0)*100),currency:data.currencyCode,paid_at:data.paidOn};const result=normalized.status==="success"?await settle(reference,normalized):{reference,status:normalized.status};res.json({success:true,data:result});}));

export async function monnifyWebhook(req:Request,res:Response,next:NextFunction){try{const connection=(await query<Connection>("SELECT id,business_id,environment,encrypted_credentials FROM integration_connections WHERE id=$1 AND kind='payment_provider' AND provider='monnify' AND status='active' AND deleted_at IS NULL",[req.params.connectionId]))[0];if(!connection?.encrypted_credentials||!req.rawBody)throw new HttpError(401,"Invalid Monnify webhook");const credentials=decryptMonnifyCredentials(connection.encrypted_credentials);const signature=String(req.headers["monnify-signature"]??"");if(!validMonnifySignature(req.rawBody,signature,credentials.secretKey))throw new HttpError(401,"Invalid Monnify signature");if(req.body.eventType==="SUCCESSFUL_TRANSACTION"){const data=req.body.eventData??{};const reference=String(data.paymentReference??"");const intent=(await query<{reference:string}>("SELECT reference FROM payment_intents WHERE reference=$1 AND business_id=$2 AND provider='monnify'",[reference,connection.business_id]))[0];if(intent)await settle(reference,{...data,status:data.paymentStatus==="PAID"?"success":"pending",amount:Math.round(Number(data.amountPaid??0)*100),currency:data.currencyCode,paid_at:data.paidOn});}await query("UPDATE integration_connections SET last_success_at=now(),last_error_code=NULL,updated_at=now() WHERE id=$1",[connection.id]);res.sendStatus(200);}catch(error){next(error);}}
