import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { Add, Bank, DocumentUpload, Link21, SearchNormal1, Setting2, ShieldTick, TickCircle, Warning2 } from "iconsax-react";
import { Link } from "react-router-dom";
import { WorkspaceShell } from "../components/WorkspaceShell";
import { Modal } from "../components/Modal";
import { api, post } from "../lib/api";
import { useSession } from "../context/SessionContext";
import { useNotifications } from "../context/NotificationContext";

type Connection={id:string;provider:string;status:string;environment:string;last_success_at?:string;capabilities:Record<string,boolean>};type Account={id:string;connection_id:string;name:string;institution_name:string;masked_account_number?:string;currency:string;current_balance:string;last_success_at?:string};type BankTx={id:string;provider_transaction_id:string;status:string;direction:string;amount:string;currency:string;description:string;narration?:string;reference?:string;counterparty_name?:string;transacted_at:string;account_name:string;reconciliation_id?:string;reconciliation_status?:string};type Candidate={id:string;bank_transaction_id:string;proposed_amount:string;score:string;reason_codes:string[];transaction_amount:string;currency:string;description:string;narration?:string;reference?:string;counterparty_name?:string;transacted_at:string;invoice_number:string;invoice_balance:string;client_name?:string;target_id:string};
export function BankingPage(){const{session}=useSession();const{notify}=useNotifications();const[connections,setConnections]=useState<Connection[]>([]);const[accounts,setAccounts]=useState<Account[]>([]);const[transactions,setTransactions]=useState<BankTx[]>([]);const[candidates,setCandidates]=useState<Candidate[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[search,setSearch]=useState("");const[connectOpen,setConnectOpen]=useState(false);const[simulateOpen,setSimulateOpen]=useState(false);const[simulation,setSimulation]=useState({amount:"",reference:"",description:"Customer transfer",counterpartyName:""});const money=(value:string|number,currency=session!.business.currency??"NGN")=>new Intl.NumberFormat(undefined,{style:"currency",currency}).format(Number(value));
async function load(){setLoading(true);setError("");try{const[c,a,t,m]=await Promise.all([api<Connection[]>("/integrations/connections",{},session!.token),api<Account[]>("/integrations/bank-accounts",{},session!.token),api<BankTx[]>("/integrations/bank-transactions",{},session!.token),api<Candidate[]>("/integrations/reconciliation/candidates",{},session!.token)]);setConnections(c.filter(row=>row.provider==="moniepoint"));setAccounts(a);setTransactions(t);setCandidates(m);}catch(reason){setError(reason instanceof Error?reason.message:"Could not load bank feeds");}finally{setLoading(false);}}useEffect(()=>{void load();},[]);
async function connect(event:FormEvent){event.preventDefault();setBusy("connect");try{await post("/integrations/banks/mock/connect",{currency:session!.business.currency??"NGN",name:"Primary business account"},session!.token);setConnectOpen(false);await load();notify({tone:"success",title:"Simulated bank connected",message:"You can now import a statement or send signed test events."});}catch(reason){setError(reason instanceof Error?reason.message:"Connection failed");}finally{setBusy("");}}
async function simulate(event:FormEvent){event.preventDefault();const connection=connections.find(row=>row.status==="active");if(!connection)return;setBusy("simulate");try{await post("/integrations/banks/mock/events",{connectionId:connection.id,payload:{eventId:`demo-${Date.now()}`,eventType:"V1_BANK_TRANSACTION",createdAt:new Date().toISOString(),data:{transactionReference:`MPT-${Date.now()}`,transactionStatus:"SUCCESS",direction:"credit",amount:Number(simulation.amount),currency:session!.business.currency??"NGN",merchantReference:simulation.reference,description:simulation.description,counterpartyName:simulation.counterpartyName,transactionTime:new Date().toISOString()}}},session!.token);setSimulateOpen(false);await load();notify({tone:"success",title:"Bank event processed",message:"The transaction was normalized and matching candidates were generated."});}catch(reason){setError(reason instanceof Error?reason.message:"Simulation failed");}finally{setBusy("");}}
async function importCsv(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];const connection=connections.find(row=>row.status==="active");if(!file||!connection)return;setBusy("import");try{const rows=parseCsv(await file.text());await post(`/integrations/banks/${connection.id}/import`,{rows},session!.token);await load();notify({tone:"success",title:"Statement imported",message:`${rows.length} rows were normalized and checked for matches.`});}catch(reason){setError(reason instanceof Error?reason.message:"Statement import failed");}finally{setBusy("");event.target.value="";}}
async function reconcile(candidate:Candidate){setBusy(candidate.id);try{await post(`/integrations/reconciliation/${candidate.bank_transaction_id}/accept`,{allocations:[{invoiceId:candidate.target_id,amount:Number(candidate.proposed_amount)}],confidence:Number(candidate.score),reason:"Accepted suggested match"},session!.token);await load();notify({tone:"success",title:"Payment reconciled",message:`${candidate.invoice_number} and its payment record were updated.`});}catch(reason){setError(reason instanceof Error?reason.message:"Could not reconcile transaction");}finally{setBusy("");}}
async function ignore(candidate:Candidate){setBusy(candidate.id);try{await post(`/integrations/reconciliation/${candidate.bank_transaction_id}/ignore`,{reason:"Not related to an open invoice"},session!.token);await load();}finally{setBusy("");}}
const visible=useMemo(()=>transactions.filter(row=>`${row.description} ${row.reference??""} ${row.counterparty_name??""}`.toLowerCase().includes(search.toLowerCase())),[transactions,search]);const active=connections.some(row=>row.status==="active");
return <WorkspaceShell title="Banking & reconciliation" description="See connected money, verify suggested matches, and keep every payment tied to its source." action={<div className="page-actions"><Link className="secondary-button" to="/banking/operations"><Setting2 size={17}/>Controls & operations</Link>{active?<><label className="secondary-button bank-import"><DocumentUpload size={17}/>{busy==="import"?"Importing…":"Import statement"}<input type="file" accept=".csv,text/csv" onChange={event=>void importCsv(event)} disabled={Boolean(busy)}/></label><button className="primary-button primary-button--compact" onClick={()=>setSimulateOpen(true)}><Add size={17}/>Simulate credit</button></>:<button className="primary-button primary-button--compact" onClick={()=>setConnectOpen(true)}><Link21 size={17}/>Connect bank</button>}</div>}>
{error&&<p className="form-error">{error}</p>}<section className="bank-health">{accounts.length?accounts.map(account=><article key={account.id}><span><Bank size={22}/></span><div><p>{account.institution_name}</p><strong>{account.name}</strong><small>{account.masked_account_number} · {account.last_success_at?`Synced ${new Date(account.last_success_at).toLocaleString()}`:"Ready"}</small></div><div><p>Current balance</p><strong>{money(account.current_balance,account.currency)}</strong><small className="connection-live"><i/>Connected · simulated</small></div></article>):<article className="bank-empty"><span><Bank size={24}/></span><div><strong>No bank feed connected</strong><p>Connect the safe simulator now. Live Moniepoint access remains behind provider approval.</p></div><button onClick={()=>setConnectOpen(true)}>Connect simulator</button></article>}</section>
<section className="reconciliation-grid"><article className="panel attention-panel"><header><div><p className="section-kicker">NEEDS ATTENTION</p><h2>Suggested matches</h2></div><span>{candidates.length}</span></header>{candidates.length?candidates.map(row=><div className="match-card" key={row.id}><div className="match-source"><span><Bank size={18}/></span><div><strong>{money(row.transaction_amount,row.currency)}</strong><small>{row.counterparty_name||row.description} · {new Date(row.transacted_at).toLocaleDateString()}</small></div><em>{Number(row.score)}% match</em></div><div className="match-arrow">↓</div><div className="match-target"><div><strong>{row.invoice_number}</strong><small>{row.client_name||"Customer"} · balance {money(row.invoice_balance,row.currency)}</small></div><div className="reason-tags">{row.reason_codes.map(reason=><span key={reason}><ShieldTick size={12}/>{reason.replaceAll("_"," ")}</span>)}</div></div><footer><button disabled={busy===row.id} onClick={()=>void ignore(row)}>Not a match</button><button disabled={busy===row.id} onClick={()=>void reconcile(row)}><TickCircle size={15}/>{busy===row.id?"Matching…":"Confirm match"}</button></footer></div>):<div className="inline-state"><TickCircle size={26}/><strong>No suggested matches</strong><p>New booked credits with invoice evidence will appear here.</p></div>}</article>
<article className="panel money-feed"><header><div><p className="section-kicker">MONEY FEED</p><h2>Bank transactions</h2></div><div className="search-box"><SearchNormal1 size={17}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search money"/></div></header>{loading?<p>Loading bank activity…</p>:visible.length?<div>{visible.map(row=><div className="money-row" key={row.id}><span className={`money-direction money-direction--${row.direction}`}>{row.direction==="credit"?"+":"−"}</span><div><strong>{row.counterparty_name||row.description}</strong><small>{new Date(row.transacted_at).toLocaleString()} · {row.reference||row.provider_transaction_id}</small></div><span className={`status status--${row.reconciliation_status?"paid":"pending"}`}>{row.reconciliation_status||row.status}</span><strong>{row.direction==="credit"?"+":"−"}{money(row.amount,row.currency)}</strong></div>)}</div>:<div className="inline-state"><Warning2 size={25}/><strong>No bank transactions yet</strong><p>Import a CSV statement or simulate a signed Moniepoint event.</p></div>}</article></section>
<Modal open={connectOpen} onClose={()=>setConnectOpen(false)} onSubmit={connect} title="Connect a bank feed" description="Use the production-shaped simulator while live Moniepoint account-feed access is being approved." submitLabel="Connect simulator" busy={busy==="connect"}><div className="connection-preview"><Bank size={26}/><div><strong>Moniepoint simulator</strong><p>Read-only accounts, signed events, transaction normalization, matching, retries, and audit history.</p></div><span>SAFE TEST</span></div></Modal>
<Modal open={simulateOpen} onClose={()=>setSimulateOpen(false)} onSubmit={simulate} title="Simulate a bank credit" description="Use an invoice number as the reference to test exact matching." submitLabel="Send signed event" busy={busy==="simulate"}><div className="form-grid"><label>Amount<input type="number" min="0.01" step="0.01" value={simulation.amount} onChange={e=>setSimulation({...simulation,amount:e.target.value})} required/></label><label>Invoice/reference<input value={simulation.reference} onChange={e=>setSimulation({...simulation,reference:e.target.value})} placeholder="LB-1001"/></label><label className="span-2">Sender name<input value={simulation.counterpartyName} onChange={e=>setSimulation({...simulation,counterpartyName:e.target.value})}/></label><label className="span-2">Description<input value={simulation.description} onChange={e=>setSimulation({...simulation,description:e.target.value})}/></label></div></Modal></WorkspaceShell>}

function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error("CSV must contain a header and at least one row");const parse=(line:string)=>{const cells:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const char=line[i];if(char==='"'&&quoted&&line[i+1]==='"'){value+='"';i++;}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){cells.push(value.trim());value="";}else value+=char;}cells.push(value.trim());return cells;};const headers=parse(lines[0]!).map(value=>value.toLowerCase().replace(/\s+/g,"_"));return lines.slice(1).map(line=>Object.fromEntries(parse(line).map((value,index)=>[headers[index],value])));}
