import { useEffect, useMemo, useState } from "react";
import { Add, DocumentText, SearchNormal1, Send2, TickCircle } from "iconsax-react";
import { Link, useNavigate } from "react-router-dom";
import { WorkspaceShell } from "../components/WorkspaceShell";
import { LoadError, SearchEmpty, TableLoading } from "../components/DataState";
import { ResourceEmpty } from "./ClientsPage";
import { useSession } from "../context/SessionContext";
import { api, post } from "../lib/api";
import type { Invoice } from "../lib/types";
import { useNotifications } from "../context/NotificationContext";

export function InvoicesPage() {
  const { session } = useSession(); const { notify } = useNotifications(); const navigate = useNavigate(); const [rows,setRows] = useState<Invoice[]>([]); const [search,setSearch] = useState(""); const [filter,setFilter] = useState("all"); const [loading,setLoading] = useState(true); const [loadError,setLoadError] = useState(""); const [workingId,setWorkingId] = useState("");
  async function load() { setLoading(true); setLoadError(""); try { setRows(await api<Invoice[]>("/resources/invoices",{},session!.token)); } catch(reason) { setLoadError(reason instanceof Error ? reason.message : "Could not load invoices"); } finally { setLoading(false); } }
  useEffect(()=>{void load();},[]);
  async function send(invoice:Invoice) { setWorkingId(invoice.id); try { await post(`/resources/invoices/${invoice.id}/send`,{},session!.token); await load(); notify({tone:"success",title:"Invoice sent",message:`${invoice.number} was delivered to ${invoice.client_email}.`}); } catch(reason) { notify({tone:"error",title:"Invoice wasn’t sent",message:reason instanceof Error ? reason.message : "Check the customer email and try again."}); } finally { setWorkingId(""); } }
  const money=(value:string,currency:string)=>new Intl.NumberFormat(undefined,{style:"currency",currency}).format(Number(value));
  const visible=useMemo(()=>rows.filter((row)=>(filter==="all"||(filter==="awaiting_review"?Number(row.pending_payment_count)>0:row.status===filter))&&`${row.number} ${row.client_name??""}`.toLowerCase().includes(search.toLowerCase())),[rows,search,filter]);
  return <WorkspaceShell title="Invoices" description="Create, deliver, and track every customer invoice." action={<Link className="primary-button primary-button--compact" to="/invoices/new"><Add size={19}/>Create invoice</Link>}>
    <section className="panel resource-panel"><div className="resource-toolbar resource-toolbar--filters"><div className="search-box"><SearchNormal1 size={18}/><input aria-label="Search invoices" value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search invoice or client"/></div><div className="filter-pills" aria-label="Invoice status">{["all","awaiting_review","draft","sent","overdue","paid"].map(value=><button key={value} className={filter===value?"active":""} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value==="sent"?"Unpaid":value.replace("_"," ")}</button>)}</div><span>{visible.length} invoices</span></div>
      {loading?<TableLoading label="Loading invoices"/>:loadError?<LoadError message={loadError} onRetry={()=>void load()}/>:visible.length?<div className="table-wrap"><table className="invoice-table"><thead><tr><th>Invoice</th><th>Client</th><th>Due</th><th>Status</th><th className="align-right">Amount</th><th className="align-right">Next action</th></tr></thead><tbody>{visible.map(invoice=><tr key={invoice.id}><td><Link className="table-primary-link" to={`/invoices/${invoice.id}`}><strong>{invoice.number}</strong>{invoice.sent_at&&<small>Sent {new Date(invoice.sent_at).toLocaleDateString()}</small>}</Link></td><td><strong>{invoice.client_name||"Walk-in customer"}</strong><small>{invoice.client_email}</small></td><td>{invoice.due_date?new Date(invoice.due_date).toLocaleDateString():"On receipt"}</td><td>{Number(invoice.pending_payment_count)>0?<span className="status status--pending">awaiting review</span>:<span className={`status status--${invoice.status}`}>{invoice.status==="sent"?"unpaid":invoice.status.replace("_"," ")}</span>}</td><td className="align-right"><strong>{money(invoice.total,invoice.currency)}</strong></td><td><div className="invoice-actions">{Number(invoice.pending_payment_count)>0?<Link className="review-link" to="/transactions">Review payment</Link>:<>{invoice.status==="draft"&&<button className="send-button" disabled={workingId===invoice.id} onClick={()=>void send(invoice)}><Send2 size={15}/>{workingId===invoice.id?"Sending…":"Send"}</button>}{["sent","part_paid","overdue"].includes(invoice.status)&&<Link className="action-complete" to={`/invoices/${invoice.id}`}>View details</Link>}{invoice.status==="paid"&&<span className="action-complete"><TickCircle size={15}/>Paid</span>}</>}</div></td></tr>)}</tbody></table></div>:search||filter!=="all"?<SearchEmpty query={search||filter}>Clear or change the current filters.</SearchEmpty>:<ResourceEmpty icon={<DocumentText size={29}/>} title="Send your first invoice" text="Create a draft and email the customer a secure payment link." action="Create an invoice" onClick={()=>navigate("/invoices/new")}/>} 
    </section>
  </WorkspaceShell>;
}
