import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft2, Printer, Send2, TickCircle, Trash } from "iconsax-react";
import { Link, useParams } from "react-router-dom";
import { WorkspaceShell } from "../components/WorkspaceShell";
import { LoadError, TableLoading } from "../components/DataState";
import { Modal } from "../components/Modal";
import { useSession } from "../context/SessionContext";
import { api, post } from "../lib/api";
import type { InvoiceDetail } from "../lib/types";
import { useNotifications } from "../context/NotificationContext";

const stages = ["draft", "sent", "overdue", "paid"];
export function InvoiceDetailPage() {
  const { id = "" } = useParams(); const { session } = useSession(); const { notify } = useNotifications(); const [invoice,setInvoice] = useState<InvoiceDetail|null>(null); const [loading,setLoading] = useState(true); const [error,setError] = useState(""); const [busy,setBusy] = useState(false); const [confirmVoid,setConfirmVoid] = useState(false);
  async function load() { setLoading(true); setError(""); try { setInvoice(await api<InvoiceDetail>(`/resources/invoices/${id}`,{},session!.token)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load invoice"); } finally { setLoading(false); } }
  useEffect(()=>{void load();},[id]);
  async function send() { setBusy(true); setError(""); try { await post(`/resources/invoices/${id}/send`,{},session!.token); await load(); notify({tone:"success",title:"Invoice sent",message:`${invoice?.number} was delivered to ${invoice?.client_email}.`}); } catch(reason) { notify({tone:"error",title:"Invoice wasn’t sent",message:reason instanceof Error ? reason.message : "Check the customer email and try again."}); } finally { setBusy(false); } }
  async function voidInvoice(event:FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await post(`/resources/invoices/${id}/void`,{},session!.token); setConfirmVoid(false); await load(); notify({tone:"warning",title:"Invoice voided",message:`${invoice?.number} can no longer be paid.`}); } catch(reason) { const message=reason instanceof Error ? reason.message : "Could not void invoice"; setError(message); notify({tone:"error",title:"Invoice wasn’t voided",message}); } finally { setBusy(false); } }
  const money=(value:string|number)=>new Intl.NumberFormat(undefined,{style:"currency",currency:invoice?.currency??session!.business.currency??"NGN"}).format(Number(value));
  if (loading) return <WorkspaceShell title="Invoice" description="Loading invoice details."><section className="panel"><TableLoading rows={6} label="Loading invoice"/></section></WorkspaceShell>;
  if (!invoice) return <WorkspaceShell title="Invoice unavailable"><section className="panel"><LoadError message={error} onRetry={()=>void load()}/></section></WorkspaceShell>;
  const balance=Math.max(0,Number(invoice.total)-Number(invoice.amount_paid)); const currentIndex=invoice.status==="cancelled"?-1:invoice.status==="part_paid"?1:stages.indexOf(invoice.status);
  return <WorkspaceShell title={invoice.number} description={`${invoice.client_name || "Walk-in customer"} · Issued ${new Date(invoice.issue_date).toLocaleDateString()}`} action={<div className="page-actions print-hidden"><button className="secondary-button" onClick={()=>window.print()}><Printer size={18}/>Print</button>{invoice.status==="draft"&&<button className="primary-button primary-button--compact invoice-send-main" disabled={busy} onClick={()=>void send()}><Send2 size={18}/>{busy?"Sending…":"Send invoice"}</button>}</div>}>
    <Link className="back-link print-hidden" to="/invoices"><ArrowLeft2 size={17}/>Back to invoices</Link>{Number(invoice.pending_payment_count)>0&&<div className="page-alert"><span><strong>Customer payment requires verification</strong><small>Review the reported cash or transfer payment before updating this invoice.</small></span><Link to="/transactions">Review payment</Link></div>}
    <section className="invoice-detail-grid"><div className="invoice-detail-main"><article className="panel lifecycle-card"><header><div><p className="section-kicker">Invoice journey</p><h2>{invoice.status==="cancelled"?"This invoice was voided":"Payment lifecycle"}</h2></div><span className={`status status--${invoice.status}`}>{invoice.status.replace("_"," ")}</span></header>{invoice.status!=="cancelled"&&<div className="lifecycle">{stages.map((stage,index)=><div className={index<=currentIndex?"complete":""} key={stage}><span>{index<currentIndex?<TickCircle size={18}/>:index+1}</span><strong>{stage==="sent"?"Unpaid":stage}</strong></div>)}</div>}</article><article className="panel invoice-document"><header><div><p className="section-kicker">Invoice details</p><h2>Items and services</h2></div></header><div className="table-wrap"><table><thead><tr><th>Description</th><th>Quantity</th><th className="align-right">Unit price</th><th className="align-right">Amount</th></tr></thead><tbody>{invoice.lines.map(line=><tr key={line.id}><td><strong>{line.description}</strong><small>{line.sku}</small></td><td>{Number(line.quantity).toLocaleString()}</td><td className="align-right">{money(line.unit_price)}</td><td className="align-right"><strong>{money(line.total)}</strong></td></tr>)}</tbody></table></div>{invoice.notes&&<div className="invoice-note"><strong>Note</strong><p>{invoice.notes}</p></div>}</article></div><aside className="invoice-detail-aside"><article className="panel balance-card"><p className="section-kicker">Balance due</p><strong>{money(balance)}</strong><span>Total {money(invoice.total)}</span><div><span>Paid</span><strong>{money(invoice.amount_paid)}</strong></div><div><span>Due date</span><strong>{invoice.due_date?new Date(invoice.due_date).toLocaleDateString():"On receipt"}</strong></div></article><article className="panel customer-card"><p className="section-kicker">Bill to</p><h3>{invoice.client_name||"Walk-in customer"}</h3>{invoice.client_email&&<p>{invoice.client_email}</p>}{invoice.client_phone&&<p>{invoice.client_phone}</p>}{invoice.client_address&&<p>{invoice.client_address}</p>}</article>{["draft","sent","overdue"].includes(invoice.status)&&<button className="danger-text-button print-hidden" onClick={()=>setConfirmVoid(true)}><Trash size={17}/>Void invoice</button>}</aside></section>
    <Modal open={confirmVoid} onClose={()=>setConfirmVoid(false)} onSubmit={voidInvoice} title={`Void ${invoice.number}?`} description="This is recorded as a permanent lifecycle change." submitLabel="Void invoice" busy={busy}><div className="decision-summary decision-summary--rejected"><strong>The customer will no longer be able to pay this invoice.</strong><p>Existing payment records are not deleted. Create a replacement invoice if the customer still needs to be billed.</p></div></Modal>
  </WorkspaceShell>;
}
