import { useState } from "react";
import { Lock1, Message, ShieldTick, TickCircle } from "iconsax-react";
import { useNavigate } from "react-router-dom";
import { WorkspaceShell } from "../components/WorkspaceShell";
import { useNotifications } from "../context/NotificationContext";
import { useSession } from "../context/SessionContext";
import { post } from "../lib/api";
import { launchMetaEmbeddedSignup } from "../lib/metaEmbeddedSignup";
type SignupSession = { appId:string;configId:string;graphVersion:string;state:string };
export function MetaWhatsAppConnectPage({onConnected}:{onConnected?:()=>void}={}){const{session}=useSession();const{notify}=useNotifications();const navigate=useNavigate();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function connect(){setBusy(true);setError("");try{const signup=await post<SignupSession>("/whatsapp/embedded-signup/session",{},session!.token);const result=await launchMetaEmbeddedSignup(signup);await post("/whatsapp/embedded-signup/complete",{...result,state:signup.state},session!.token);await post("/whatsapp/production/templates/sync",{},session!.token);notify({tone:"success",title:"WhatsApp Business connected",message:"The number was verified with Meta and its templates are synchronized."});if(onConnected)onConnected();else navigate("/whatsapp");}catch(reason){setError(reason instanceof Error?reason.message:"WhatsApp connection could not be completed");}finally{setBusy(false);}}return <WorkspaceShell title="WhatsApp Business" description="Connect your WhatsApp account to start conversations and automations.">{error&&<p className="form-error">{error}</p>}<section className="panel meta-connect-card"><span className="whatsapp-logo"><Message size={23}/></span><p className="section-kicker">META EMBEDDED SIGNUP</p><h2>Connect without sharing your password</h2><p>You will continue to Meta to choose or create your business account, WhatsApp account, and phone number. LemonBooks only receives the permissions needed to send and receive business messages.</p><div className="meta-connect-steps"><span><TickCircle size={18}/><strong>Choose your Meta business</strong></span><span><TickCircle size={18}/><strong>Select your WhatsApp number</strong></span><span><ShieldTick size={18}/><strong>Review and approve permissions</strong></span><span><Lock1 size={18}/><strong>Credentials encrypted by LemonBooks</strong></span></div><button className="primary-button" disabled={busy} onClick={()=>void connect()}>{busy?"Opening Meta…":"Continue with Facebook"}</button><small>Only a LemonBooks owner or administrator can connect or replace this integration.</small></section></WorkspaceShell>}
