import { ArrowLeft2, Lock1, Message, ShieldTick, TickCircle } from "iconsax-react";

export function PrivacyPolicyPage() {
  return <main className="policy-page">
    <header className="policy-header"><a className="brand" href="/"><img className="brand-mark" src="/brand/lemonbooks-logo-mark.png" alt=""/><span>LemonBooks</span></a><nav><a href="/privacy" aria-current="page">Privacy</a><a href="/terms">Terms</a><a href="/data-deletion">Data deletion</a></nav><a href="mailto:privacy@lemonbooks.io">privacy@lemonbooks.io</a></header>
    <section className="policy-hero"><span className="policy-icon"><Lock1 size={26}/></span><p className="eyebrow">PRIVACY AT LEMONBOOKS</p><h1>Privacy policy</h1><p>This policy explains what information LemonBooks collects, why we use it, how we protect it, and the choices available to you.</p><small>Effective and last updated: September 5, 2026</small></section>
    <div className="policy-layout">
      <aside><strong>On this page</strong><a href="#scope">Scope</a><a href="#collect">Information we collect</a><a href="#use">How we use information</a><a href="#sharing">How information is shared</a><a href="#whatsapp">WhatsApp and integrations</a><a href="#retention">Retention and security</a><a href="#rights">Your rights</a><a href="#contact">Contact us</a></aside>
      <article className="policy-content">
        <section className="policy-summary"><ShieldTick size={22}/><div><strong>Our commitment</strong><p>LemonBooks uses business and personal information to provide financial operations, invoicing, payment, reconciliation, inventory, customer communication, and related services. We do not sell personal information.</p></div></section>
        <section id="scope"><span className="policy-step">1</span><div><h2>Scope and who we are</h2><p>This Privacy Policy applies to LemonBooks websites, applications, customer portals, public invoice pages, support channels, WhatsApp integrations, and related services (the “Services”). “LemonBooks,” “we,” “our,” and “us” refer to the LemonBooks entity responsible for the Services.</p><p>A business using LemonBooks may provide us with information about its customers, personnel, suppliers, and transactions. For that information, the business determines why it is processed and LemonBooks generally acts as its service provider or processor. Contact that business first if your request concerns information it controls.</p></div></section>
        <section id="collect"><span className="policy-step">2</span><div><h2>Information we collect</h2><p>Depending on how you use the Services, we may collect:</p><ul><li><strong>Account and business information:</strong> name, email address, telephone number, business name, address, role, workspace membership, verification status, and preferences.</li><li><strong>Financial and operational records:</strong> invoices, estimates, orders, payments, payment claims, bank-transaction references, reconciliation decisions, inventory, expenses, customers, and suppliers.</li><li><strong>Integration information:</strong> identifiers, authorization grants, connection status, masked account details, webhook events, and encrypted credentials for services you choose to connect.</li><li><strong>Communications:</strong> support correspondence and, where WhatsApp is connected, phone numbers, profile names, message content, message status, template, and conversation metadata.</li><li><strong>Technical and usage information:</strong> IP address, browser and device information, timestamps, security events, application activity, diagnostics, and cookies or similar technologies needed to operate the Services.</li></ul><p>Please do not submit sensitive personal information that is not necessary for a legitimate business workflow.</p></div></section>
        <section id="use"><span className="policy-step">3</span><div><h2>How we use information</h2><p>We use information to provide, secure, maintain, and improve the Services; authenticate users; create and manage workspaces; process instructions; generate records and reports; deliver invoices and messages; connect authorized providers; reconcile payments; provide support; prevent fraud and abuse; comply with law; and communicate operational or service information.</p><p>Where required, we rely on performance of a contract, legitimate business interests, legal obligations, or consent. Automated features may help classify messages, suggest matches, or prepare records. Material financial actions should remain subject to the permissions and confirmations presented in the product.</p></div></section>
        <section id="sharing"><span className="policy-step">4</span><div><h2>How information is shared</h2><p>We may share information with:</p><ul><li>authorized users and administrators of the relevant LemonBooks workspace;</li><li>infrastructure, hosting, communications, analytics, security, and support providers working under appropriate obligations;</li><li>payment gateways, banks, and other integrations when you direct LemonBooks to connect or transact with them;</li><li>Meta and WhatsApp when a business enables WhatsApp Business functionality;</li><li>professional advisers, regulators, law-enforcement authorities, or other parties when reasonably necessary to comply with law, protect rights, or prevent harm; and</li><li>a successor in connection with a merger, financing, acquisition, reorganization, or sale, subject to appropriate safeguards.</li></ul><p>We do not sell or rent message content, customer lists, or financial records for third-party advertising.</p></div></section>
        <section id="whatsapp"><span className="policy-step">5</span><div><h2>WhatsApp Business and connected services</h2><p>When a business connects WhatsApp, LemonBooks receives and processes information made available through the WhatsApp Business Platform to deliver messaging, automation, customer support, order, invoice, and record-management features. This may include WhatsApp Business Account and phone-number identifiers, contacts, messages, media references, delivery events, and approved templates.</p><p>Meta and WhatsApp independently process information under their own terms and privacy policies. A business administrator can disconnect the integration, and verified users may request deletion using our <a href="/data-deletion">Data Deletion Instructions</a>. Disconnecting an integration does not automatically erase accounting records that must remain available to the business or be retained by law.</p></div></section>
        <section id="retention"><span className="policy-step">6</span><div><h2>Retention, storage, and security</h2><p>We retain information for as long as reasonably necessary to provide the Services, maintain legitimate business records, resolve disputes, enforce agreements, prevent abuse, and comply with tax, accounting, legal, and regulatory requirements. Retention periods vary by the type of information and the business relationship.</p><p>We use administrative, technical, and organizational safeguards designed to protect information, including access controls, tenant separation, encrypted transport, protected integration credentials, monitoring, and backups. No internet service can guarantee absolute security. Notify us promptly if you believe an account or integration has been compromised.</p><p>Information may be processed in countries other than where you live. Where required, we use lawful transfer mechanisms and safeguards appropriate to the information and destination.</p></div></section>
        <section id="rights"><span className="policy-step">7</span><div><h2>Your choices and rights</h2><p>Depending on your location and relationship with LemonBooks, you may have rights to access, correct, export, restrict, object to, or delete personal information, or withdraw consent. You may also complain to the relevant data-protection authority.</p><p>Workspace administrators can update much of their business information in LemonBooks. For other requests, email <a href="mailto:privacy@lemonbooks.io">privacy@lemonbooks.io</a>. We may verify your identity and authority before acting. If a LemonBooks customer controls the information, we may direct your request to that business.</p><p>See our <a href="/data-deletion">Data Deletion Instructions</a> for account and WhatsApp deletion requests.</p></div></section>
        <section id="children"><span className="policy-step">8</span><div><h2>Children and policy changes</h2><p>The Services are intended for businesses and are not directed to children. We do not knowingly create accounts for children who cannot legally consent to the processing of their information.</p><p>We may update this policy as the Services or applicable requirements change. We will post the revised policy here, update the effective date, and provide additional notice when a change is material and notice is required.</p></div></section>
        <section className="policy-contact" id="contact"><Message size={24}/><div><h2>Contact our privacy team</h2><p>Questions or requests can be sent to <a href="mailto:privacy@lemonbooks.io">privacy@lemonbooks.io</a>. Product-support questions can be sent to <a href="mailto:support@lemonbooks.io">support@lemonbooks.io</a>.</p></div></section>
      </article>
    </div>
    <footer className="policy-footer"><span>© 2026 LemonBooks</span><a href="/terms">Terms of service</a><a href="/data-deletion">Data deletion</a><a href="/"><ArrowLeft2 size={15}/>Return to LemonBooks</a><span><TickCircle size={15}/>Public privacy policy</span></footer>
  </main>;
}
