import { FormEvent, useEffect, useState } from "react";
import { Edit2, People } from "iconsax-react";
import { AddButton, WorkspaceShell } from "../components/WorkspaceShell";
import { Modal } from "../components/Modal";
import { ResourceEmpty } from "./ClientsPage";
import { useSession } from "../context/SessionContext";
import { api, patch, post } from "../lib/api";
import type { TeamMember } from "../lib/types";

const empty = { name: "", email: "", password: "", role: "member" as TeamMember["role"] };
export function TeamPage() {
  const { session } = useSession(); const [rows, setRows] = useState<TeamMember[]>([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<TeamMember | null>(null); const [form, setForm] = useState(empty); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const canManage = ["owner", "admin"].includes(session!.user.role);
  const load = () => api<TeamMember[]>("/team", {}, session!.token).then(setRows); useEffect(() => { void load(); }, []);
  function showForm(member?: TeamMember) { setEditing(member ?? null); setForm(member ? { name: member.name, email: member.email, password: "", role: member.role } : empty); setError(""); setOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { if (editing) await patch(`/team/${editing.id}`, { name: form.name, role: form.role }, session!.token); else await post("/team", form, session!.token); setOpen(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save team member"); } finally { setBusy(false); } }
  return <WorkspaceShell title="Team" description="Control who can work inside this business tenant." action={canManage ? <AddButton onClick={() => showForm()}>Add team member</AddButton> : undefined}><section className="panel resource-panel">{rows.length ? <div className="table-wrap"><table><thead><tr><th>Team member</th><th>Email</th><th>Role</th><th>Joined</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><div className="identity"><span>{row.name.charAt(0)}</span><strong>{row.name}</strong></div></td><td>{row.email}</td><td><span className="type-pill">{row.role}</span></td><td>{new Date(row.created_at).toLocaleDateString()}</td><td>{canManage && row.role !== "owner" && <button className="icon-button" onClick={() => showForm(row)}><Edit2 size={17} /></button>}</td></tr>)}</tbody></table></div> : <ResourceEmpty icon={<People size={29} />} title="Build your team" text="Add colleagues to this business workspace and choose what role they hold." action="Add a team member" onClick={() => showForm()} />}</section><Modal open={open} onClose={() => setOpen(false)} onSubmit={submit} title={editing ? "Edit team member" : "Add team member"} description="Membership is limited to this business tenant." submitLabel={editing ? "Save changes" : "Add member"} busy={busy}><div className="form-grid"><label className="span-2">Name<input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label className="span-2">Email<input type="email" value={form.email} disabled={Boolean(editing)} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label>{!editing && <label className="span-2">Temporary password<input type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /><small>Share this securely. The member can use it to sign in.</small></label>}<label className="span-2">Role<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value as TeamMember["role"] })}><option value="admin">Admin</option><option value="accountant">Accountant</option><option value="member">Member</option></select></label></div>{error && <p className="form-error">{error}</p>}</Modal></WorkspaceShell>;
}
