import { ArrowLeft2, DocumentText, Message, ShieldTick, TickCircle } from "iconsax-react";

export function TermsPage() {
  return <main className="policy-page">
    <header className="policy-header"><a className="brand" href="/"><span className="brand-mark">L</span><span>LemonBooks</span></a><nav><a href="/privacy">Privacy</a><a href="/terms" aria-current="page">Terms</a><a href="/data-deletion">Data deletion</a></nav><a href="mailto:legal@lemonbooks.io">legal@lemonbooks.io</a></header>
    <section className="policy-hero"><span className="policy-icon"><DocumentText size={26}/></span><p className="eyebrow">LEMONBOOKS SERVICE TERMS</p><h1>Terms of service</h1><p>These terms govern access to LemonBooks and set clear responsibilities for using our financial operations, messaging, and integration services.</p><small>Effective and last updated: September 5, 2026</small></section>
    <div className="policy-layout">
      <aside><strong>On this page</strong><a href="#agreement">Agreement</a><a href="#accounts">Accounts</a><a href="#services">Using the Services</a><a href="#financial">Financial information</a><a href="#integrations">Connected services</a><a href="#content">Business data</a><a href="#fees">Fees</a><a href="#availability">Availability</a><a href="#termination">Termination</a><a href="#liability">Liability</a><a href="#contact">Contact</a></aside>
      <article className="policy-content">
        <section className="policy-summary"><ShieldTick size={22}/><div><strong>A dependable business relationship</strong><p>LemonBooks provides tools that help businesses organize operations. You remain responsible for your business decisions, records, communications, taxes, and compliance obligations.</p></div></section>
        <section id="agreement"><span className="policy-step">1</span><div><h2>Agreement and eligibility</h2><p>By creating an account, accessing LemonBooks, or using our websites, applications, customer portals, public payment pages, messaging features, APIs, or integrations (collectively, the “Services”), you agree to these Terms and our <a href="/privacy">Privacy Policy</a>. If you use LemonBooks for an organization, you confirm that you have authority to accept these Terms for that organization.</p><p>You must be legally capable of entering a binding agreement and must provide accurate account and business information. If you do not agree to these Terms, do not use the Services.</p></div></section>
        <section id="accounts"><span className="policy-step">2</span><div><h2>Accounts and authorized users</h2><p>You are responsible for protecting account credentials, keeping administrator and user access current, and promptly notifying us of suspected unauthorized access. Actions taken through an authorized account are treated as instructions from the applicable business unless we know the account has been compromised.</p><p>Workspace owners control user invitations, roles, connected accounts, and business records. You must not share credentials in a manner that bypasses access controls or permit anyone to use the Services unlawfully.</p></div></section>
        <section id="services"><span className="policy-step">3</span><div><h2>Acceptable use</h2><p>You may use the Services only for legitimate business purposes and in accordance with applicable law. You must not use LemonBooks to commit fraud, misrepresent transactions, send unlawful or unsolicited communications, infringe rights, distribute malicious code, probe security, disrupt the Services, evade usage restrictions, or access another business’s information without authorization.</p><p>You are responsible for obtaining appropriate permission before entering personal information, connecting third-party accounts, or contacting customers through LemonBooks.</p></div></section>
        <section id="financial"><span className="policy-step">4</span><div><h2>Financial records and decisions</h2><p>LemonBooks supports invoicing, payment recording, reconciliation, inventory, reporting, and related workflows. It is not a bank, payment institution, accounting firm, tax adviser, auditor, or legal adviser. Unless expressly stated otherwise, LemonBooks does not hold customer funds or guarantee settlement by a bank or payment provider.</p><p>Automated matches, classifications, extracts, forecasts, and suggested records may contain errors. You are responsible for reviewing material actions, maintaining source documents, correcting records, and obtaining professional advice where appropriate. Your bank, payment provider, or official statement remains authoritative for settlement and account balances.</p></div></section>
        <section id="integrations"><span className="policy-step">5</span><div><h2>WhatsApp, payments, banks, and integrations</h2><p>If you connect a third-party service, you authorize LemonBooks to exchange information and act on permitted instructions to provide the requested functionality. Third-party services—including Meta, WhatsApp, payment gateways, and banks—operate under their own terms, availability, pricing, and privacy practices.</p><p>We do not control and are not responsible for a third party’s approval, verification, suspension, outage, rejected payment, delayed settlement, messaging restriction, or changes to its service. You must comply with applicable third-party policies, including WhatsApp messaging and template requirements.</p></div></section>
        <section id="content"><span className="policy-step">6</span><div><h2>Your business data</h2><p>You retain ownership of information and content you submit to LemonBooks. You grant us the limited rights needed to host, process, transmit, back up, and display that information to operate, secure, support, and improve the Services.</p><p>You represent that you have the rights and lawful basis necessary to provide the information. You are responsible for the accuracy and legality of invoices, messages, product information, customer details, and other business content. Our handling of personal information is described in the <a href="/privacy">Privacy Policy</a>.</p></div></section>
        <section id="fees"><span className="policy-step">7</span><div><h2>Plans, fees, and taxes</h2><p>Some Services may require a paid plan or incur provider charges. Pricing, billing period, usage limits, and applicable fees will be presented before purchase or in an order form. Unless required by law or stated otherwise, paid fees are non-refundable.</p><p>You are responsible for applicable taxes and third-party charges, including payment processing, messaging, currency conversion, bank, telecommunications, and data charges. We may change pricing with reasonable advance notice where required.</p></div></section>
        <section id="availability"><span className="policy-step">8</span><div><h2>Availability and changes</h2><p>We work to provide reliable Services but do not guarantee uninterrupted or error-free operation. Maintenance, security incidents, internet conditions, third-party outages, and events outside our reasonable control may affect availability. Features may be changed, limited, suspended, or discontinued as the product and provider requirements evolve.</p><p>To the extent permitted by law, the Services are provided “as is” and “as available,” without implied warranties of merchantability, fitness for a particular purpose, or non-infringement.</p></div></section>
        <section id="termination"><span className="policy-step">9</span><div><h2>Suspension, termination, and deletion</h2><p>You may stop using LemonBooks at any time. We may suspend or terminate access when reasonably necessary to protect the Services or others, respond to legal requirements, address non-payment, or investigate a material breach of these Terms. Where appropriate, we will provide notice and an opportunity to resolve the issue.</p><p>Termination does not eliminate accrued payment obligations or provisions intended to survive. Data export, retention, and deletion are subject to plan capabilities, our Privacy Policy, legal obligations, backup cycles, and the instructions on our <a href="/data-deletion">Data Deletion page</a>.</p></div></section>
        <section id="liability"><span className="policy-step">10</span><div><h2>Liability and general terms</h2><p>To the maximum extent permitted by applicable law, LemonBooks will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, revenue, data, goodwill, or business opportunity arising from use of the Services. Any aggregate liability will be limited to amounts paid to LemonBooks for the affected Services during the twelve months before the event giving rise to the claim, unless applicable law requires otherwise.</p><p>You are responsible for claims resulting from your unlawful use, business content, communications, or violation of third-party rights. These Terms, together with applicable order forms and policies, form the agreement between you and LemonBooks. If part of these Terms is unenforceable, the remaining provisions continue to apply. We may update these Terms and will provide notice of material changes where required.</p></div></section>
        <section className="policy-contact" id="contact"><Message size={24}/><div><h2>Questions about these terms</h2><p>Email <a href="mailto:legal@lemonbooks.io">legal@lemonbooks.io</a>. Product-support questions can be sent to <a href="mailto:support@lemonbooks.io">support@lemonbooks.io</a>.</p></div></section>
      </article>
    </div>
    <footer className="policy-footer"><span>© 2026 LemonBooks</span><a href="/privacy">Privacy policy</a><a href="/data-deletion">Data deletion</a><a href="/"><ArrowLeft2 size={15}/>Return to LemonBooks</a><span><TickCircle size={15}/>Public service terms</span></footer>
  </main>;
}
