import { useEffect, useMemo, useState } from "react";
import { Card, CloseCircle, DocumentDownload, MoneyRecive, SearchNormal1, TickCircle, Warning2 } from "iconsax-react";
import { Link } from "react-router-dom";
import { WorkspaceShell } from "../components/WorkspaceShell";
import { LoadError, SearchEmpty, TableLoading } from "../components/DataState";
import { Modal } from "../components/Modal";
import { useSession } from "../context/SessionContext";
import { API_URL, api, patch } from "../lib/api";
import { useNotifications } from "../context/NotificationContext";

type Claim = { id:string; method:string; payer_name:string; paid_to?:string; amount:string; paid_at:string; receipt_name?:string; status:string; invoice_number:string; client_name?:string };
type PaymentRecord = { id:string; invoice_id?:string; invoice_number?:string; client_name?:string; amount:string; currency:string; method:string; provider:string; reference?:string; status:string; received_at:string };
type Decision = { claim: Claim; status: "approved" | "rejected" } | null;
type View = "ledger" | "review";

export function TransactionsPage() {
  const { session }=useSession(); const { notify }=useNotifications(); const [payments,setPayments]=useState<PaymentRecord[]>([]); const [claims,setClaims]=useState<Claim[]>([]); const [view,setView]=useState<View>("ledger"); const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState(""); const [actionError,setActionError]=useState(""); const [busy,setBusy]=useState(""); const [decision,setDecision]=useState<Decision>(null); const [search,setSearch]=useState(""); const [filter,setFilter]=useState("all");
  async function load(){setLoading(true);setLoadError("");try{const [paymentRows,claimRows]=await Promise.all([api<PaymentRecord[]>("/resources/payments",{},session!.token),api<Claim[]>("/payment-claims",{},session!.token)]);setPayments(paymentRows);setClaims(claimRows);}catch(reason){setLoadError(reason instanceof Error?reason.message:"Could not load payments");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function review(){if(!decision)return;setBusy(decision.claim.id);setActionError("");try{const completed=decision;await patch(`/payment-claims/${completed.claim.id}`,{status:completed.status},session!.token);setDecision(null);await load();notify({tone:completed.status==="approved"?"success":"warning",title:completed.status==="approved"?"Payment approved":"Payment rejected",message:completed.status==="approved"?`${completed.claim.invoice_number} was updated and the payment is now in the ledger.`:`${completed.claim.invoice_number} was left unpaid.`});}catch(reason){const message=reason instanceof Error?reason.message:"Could not review payment";setActionError(message);notify({tone:"error",title:"Review wasn’t saved",message});}finally{setBusy("");}}
  async function receipt(id:string){setActionError("");try{const response=await fetch(`${API_URL}/api/v3/payment-claims/${id}/receipt`,{headers:{Authorization:`Bearer ${session!.token}`}});if(!response.ok)throw new Error("Receipt could not be opened");const url=URL.createObjectURL(await response.blob());window.open(url,"_blank","noopener");setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(reason){const message=reason instanceof Error?reason.message:"Receipt could not be opened";setActionError(message);notify({tone:"error",title:"Receipt unavailable",message});}}
  const pending=claims.filter(claim=>claim.status==="pending"); const total=payments.reduce((sum,payment)=>sum+Number(payment.amount),0); const businessCurrency=session!.business.currency??"NGN"; const money=(value:string|number,currency=businessCurrency)=>new Intl.NumberFormat(undefined,{style:"currency",currency}).format(Number(value));
  const visiblePayments=useMemo(()=>payments.filter(row=>(filter==="all"||row.method===filter||row.provider===filter)&&`${row.invoice_number??""} ${row.client_name??""} ${row.reference??""}`.toLowerCase().includes(search.toLowerCase())),[payments,search,filter]);
  const visibleClaims=useMemo(()=>claims.filter(row=>(filter==="all"||row.status===filter)&&`${row.invoice_number} ${row.payer_name} ${row.client_name??""}`.toLowerCase().includes(search.toLowerCase())),[claims,search,filter]);
  function changeView(next:View){setView(next);setFilter(next==="review"?"pending":"all");setSearch("");}
  return <WorkspaceShell title="Payments" description="Track confirmed money in and review customer-reported payments.">
    <section className="payment-summary"><article><span><MoneyRecive size={20}/></span><div><p>Confirmed payments</p><strong>{loading?"—":money(total)}</strong><small>{payments.length} ledger entries</small></div></article><article><span className="payment-summary__warning"><Warning2 size={20}/></span><div><p>Needs review</p><strong>{loading?"—":pending.length}</strong><small>{pending.length?money(pending.reduce((sum,row)=>sum+Number(row.amount),0)):"Nothing waiting"}</small></div></article></section>
    <div className="payment-view-tabs" role="tablist" aria-label="Payment views"><button role="tab" aria-selected={view==="ledger"} className={view==="ledger"?"active":""} onClick={()=>changeView("ledger")}><span>Payment ledger</span><small>All confirmed payments</small></button><button role="tab" aria-selected={view==="review"} className={view==="review"?"active":""} onClick={()=>changeView("review")}><span>Needs review {pending.length>0&&<em>{pending.length}</em>}</span><small>Cash and transfer reports</small></button></div>
    <section className="panel resource-panel"><div className="resource-toolbar resource-toolbar--filters"><div className="search-box"><SearchNormal1 size={18}/><input aria-label="Search payments" value={search} onChange={event=>setSearch(event.target.value)} placeholder={view==="ledger"?"Search invoice, customer, or reference":"Search report or customer"}/></div><div className="filter-pills" aria-label="Payment filter">{(view==="ledger"?["all","paystack","card","transfer","cash"]:["all","pending","approved","rejected"]).map(value=><button key={value} className={filter===value?"active":""} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{value}</button>)}</div><span>{view==="ledger"?visiblePayments.length:visibleClaims.length} records</span></div>
      {loading?<TableLoading label="Loading payments"/>:loadError?<LoadError message={loadError} onRetry={()=>void load()}/>:view==="ledger"?<Ledger rows={visiblePayments} money={money} search={search||filter}/>:<ReviewQueue rows={visibleClaims} money={row=>money(row.amount)} search={search||filter} onReceipt={receipt} onDecision={setDecision}/>} 
    </section>
    <Modal open={Boolean(decision)} onClose={()=>setDecision(null)} onSubmit={event=>{event.preventDefault();void review();}} title={decision?.status==="approved"?"Approve this payment?":"Reject this payment?"} description={decision?`${decision.claim.payer_name} reported ${money(decision.claim.amount)} for ${decision.claim.invoice_number}.`:undefined} submitLabel={decision?.status==="approved"?"Approve payment":"Reject payment"} busy={Boolean(busy)}><div className={`decision-summary decision-summary--${decision?.status}`}><strong>{decision?.status==="approved"?"The invoice balance will update and this payment will enter the ledger.":"The invoice balance will not change."}</strong><p>Confirm that the payment details and proof match your records before continuing.</p></div>{actionError&&<p className="form-error" role="alert">{actionError}</p>}</Modal>
  </WorkspaceShell>;
}

function Ledger({rows,money,search}:{rows:PaymentRecord[];money:(value:string|number,currency?:string)=>string;search:string}){if(!rows.length)return search&&search!=="all"?<SearchEmpty query={search}/>:<div className="inline-state"><span className="feature-hero__icon"><Card size={25}/></span><strong>No confirmed payments yet</strong><p>Paystack payments and approved cash or transfer reports will appear here.</p></div>;return <div className="table-wrap"><table className="payment-table"><thead><tr><th>Payment</th><th>Invoice</th><th>Customer</th><th>Method</th><th>Status</th><th className="align-right">Amount</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.provider==="paystack"?"Paystack payment":"Recorded payment"}</strong><small>{new Date(row.received_at).toLocaleString()}</small></td><td>{row.invoice_id?<Link className="table-primary-link" to={`/invoices/${row.invoice_id}`}><strong>{row.invoice_number}</strong></Link>:<span>Unallocated</span>}</td><td>{row.client_name||"—"}</td><td><span className="type-pill">{row.method}</span><small>{row.provider}</small></td><td><span className="status status--paid">confirmed</span></td><td className="align-right"><strong>{money(row.amount,row.currency)}</strong><small>{row.reference}</small></td></tr>)}</tbody></table></div>}

function ReviewQueue({rows,money,search,onReceipt,onDecision}:{rows:Claim[];money:(row:Claim)=>string;search:string;onReceipt:(id:string)=>Promise<void>;onDecision:(decision:Decision)=>void}){if(!rows.length)return search&&search!=="all"?<SearchEmpty query={search}>Clear or change the current filters.</SearchEmpty>:<div className="inline-state"><span className="feature-hero__icon"><TickCircle size={25}/></span><strong>Nothing needs review</strong><p>Customer-reported cash and transfer payments will appear here.</p></div>;return <div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Reported by</th><th>Method</th><th>Paid</th><th>Proof</th><th>Status</th><th className="align-right">Review</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.invoice_number}</strong><small>{row.client_name}</small></td><td><strong>{row.payer_name}</strong><small>{row.paid_to&&`Paid to ${row.paid_to}`}</small></td><td><span className="type-pill">{row.method}</span></td><td><strong>{money(row)}</strong><small>{new Date(row.paid_at).toLocaleDateString()}</small></td><td>{row.receipt_name?<button className="icon-button" onClick={()=>void onReceipt(row.id)} aria-label={`Open receipt for ${row.invoice_number}`}><DocumentDownload size={17}/></button>:"—"}</td><td><span className={`status status--${row.status}`}>{row.status}</span></td><td><div className="review-actions">{row.status==="pending"?<><button className="approve-button" onClick={()=>onDecision({claim:row,status:"approved"})}><TickCircle size={15}/>Approve</button><button className="reject-button" onClick={()=>onDecision({claim:row,status:"rejected"})}><CloseCircle size={15}/>Reject</button></>:<span className="action-complete"><TickCircle size={14}/>Reviewed</span>}</div></td></tr>)}</tbody></table></div>}
